live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
decorations = "full"

[shell]
program="pwsh"