theme = "zed_onedark"

[keys.normal]
"S-v" = ["extend_to_line_bounds", "select_mode"]

[keys.insert]

[keys.normal.space]

[editor]
end-of-line-diagnostics = "hint"

[editor.lsp]
enable = true
display-messages = true
# display-inlay-hints = false 
snippets = true

[editor.soft-wrap]
enable = true
max-wrap = 100 # increase value to reduce forced mid-word wrapping
max-indent-retain = 100
wrap-indicator = ">> "  # set wrap-indicator to "" to hide it
